version: "3"
services:
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - 'postgres'
  postgres:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'myapp_development'
      PG_HOST: localhost
    ports:
      - "5432"
